spring:
  application:
    name: microservice-cloud-consumer-product

#server:
#  port: 80
#eureka:
#  client:
#    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
#    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
#    serviceUrl:
#      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
#spring:
#  profiles: dev # 开发环境
#  application:
#    name: microservice-consumer-product # ******服务名******
#feign:
#  hystrix:
#    enabled: true

#server:
#  port: 80
#
#eureka:
#  client:
#    registerWithEureka: false # 服务注册开关
#    fetchRegistry: true # 服务发现开关
#    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
#      defaultZone: http://eureka6002.com:6002/eureka/,http://eureka6001.com:6001/eureka/
#feign:
#  hystrix:
#    enabled: true